env:
  - IMAGE_TAG={{.Tag}}

project_name: piggybankctl

builds:
  - ldflags: "-extldflags= -w -X 'github.com/hooksie1/piggybank/cmd.Version={{.Tag}}'"
    flags:
      - -mod=vendor
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
source:
  enabled: true
